version: "3.9"

services:
  db:
    image: postgres:13
    container_name: tms
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-nextjs_db}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgrespassword}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
